from typing import Any, Dict, List, Annotated, TypedDict
from langgraph.graph import StateGraph
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class AgentState(TypedDict):
    """Full state representation flowing along the agent graph.

    Attributes:
        prompt: Initial user input.
        queries: Search queries generated by the agent.
        urls: Discovered search results.
        documents: Crawled document payloads or retrieved semantic chunks.
        indexed_count: Total document chunks indexed in the search store.
        answer: Grounded synthesized response to the prompt.
        messages: Conversation history for the tool-calling ReAct agent loop.
    """
    prompt: str
    queries: List[str]
    urls: List[str]
    documents: List[Dict[str, Any]]
    indexed_count: int
    answer: str
    messages: Annotated[List[BaseMessage], add_messages]


def build_agent_graph(
    indexer=None,
    max_queries: int = 4,
    num_results_per_query: int = 3,
    mode: str = "linear",
) -> StateGraph:
    """
    Builds and compiles the StateGraph LangGraph for the autonomous agent.

    Supported Modes:
      1. 'linear': A deterministic sequential pipeline (delegated to src.nodes.graph_linear)
      2. 'react': A dynamic tool-calling ReAct agent loop (delegated to src.nodes.graph_react)
    """
    if mode == "linear":
        from src.nodes.graph_linear import build_linear_graph
        return build_linear_graph(
            AgentState=AgentState,
            indexer=indexer,
            max_queries=max_queries,
            num_results_per_query=num_results_per_query,
        )
    elif mode == "react":
        from src.nodes.graph_react import build_react_graph
        return build_react_graph(
            AgentState=AgentState,
            indexer=indexer,
            max_queries=max_queries,
            num_results_per_query=num_results_per_query,
        )
    else:
        raise ValueError(f"Unknown build mode: '{mode}'. Supported modes are: ['linear', 'react']")
